### ISSUE TITLE
Binary gate target and control are in reverse order

### ISSUE THREAD

**Issue by BAMF0** [DATX11-22/Quaru#14] opened 2023-02-21 14:13 UTC
Entangling qubit `i` and `i+1` in the first bell state is expected to be performed by:
```
hadamard(i)
cnot(i,i+1)
```
but is currently done by:

```
hadamard(i+1)
cnot(i,i+1)
```

**Comment by edvinsternvik** [comment] 2023-02-22 11:56
As discussed in the meeting, this is caused by two separate issues.
First issue: apply assumes that the first parameter to cnot is the target when it should be the second.
Second issue: The control bit is assumed to be one greater than the target bit, but in the expected behavior described it should be the one below.

The first issue is fixed by: #17 
The second issue will be fixed by: #13

**Comment by edvinsternvik** [comment] 2023-02-28 12:57
The underlying target array representation for cnot(for example) should be [target, control]

**Comment by edvinsternvik** [comment] 2023-02-28 12:59
But we still want the interface function (operation.cnot) to have the arguments in the order control, target in order to be consistent with OpenQASM

**Closed** 2023-03-03 11:00 UTC
Labels: bug
